on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - master
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ github.token }}
concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}/${{ github.job }}
jobs:
  test:
    name: ${{ github.job }} ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: env | sort
      - run: echo "${{ toJSON(github) }}"
      - uses: rekgrpth/git-clone-action@v1
      - run: ls -Rlan "${HOME}"
      - run: "${GITHUB_WORKSPACE}/.github/test.sh"
