on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - master
  workflow_dispatch:
jobs:
  test:
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -lan "${HOME}"
      - run: env | sort
      - run: echo "${{ toJSON(github) }}"
      - uses: rekgrpth/git-clone-action@v1
