on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  merge:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: echo "${{ toJSON(github) }}"
      - uses: rekgrpth/git-clone-action@v1
