on:
  push:
    branches:
      - a
      - b
  workflow_dispatch:
jobs:
  test:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: actions/checkout@v2
        with:
          ref: b
      - uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value=oracle
