on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - master
  workflow_dispatch:
jobs:
  test:
    name: ${{ github.event_name }} ${{ github.event.repository.name }} ${{ github.event.client_payload.repository }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
#      - run: echo "${{ github.event.repository.full_name }} from ${{ github.event.client_payload.repository }}"
#      - run: echo "${{ github.event.repository.full_name }}"
#      - run: echo "${{ github.event.actor.login }}"
#      - run: echo "${{ github.event.repo.name }}"
#      - run: echo "${{ github.event.type }}"
#      - run: echo "${{ toJSON(github.event.client_payload) }}"
      - run: echo "${{ toJSON(github) }}"
