on:
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  test:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
#      - run: echo "${{ toJSON(github.event) }}"
      - run: echo "${{ github.event.client_payload.repository }}"
