on:
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  test:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
      - run: echo "${{ github.event }}"
