on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - master
  workflow_dispatch:
jobs:
  test:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.actor.login }}"
      - run: echo "${{ github.event.repo.name }}"
      - run: echo "${{ github.event.type }}"
      - run: echo "${{ github.event.client_payload }}"
      - run: echo "${{ toJSON(github.event) }}"
